### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by frostxn** [Danidev819/MCP-Snippets#1]
why did you steal my main menu and claim it as yours.
credit me bruh

**Comment by Danidev819** [comment]
I didn't know your name, it's not all skidded anyway

**Comment by frostxn** [comment]
im zelkden, the one that made the gui in the first place

**Comment by frostxn** [comment]
also yes im aussied

**Comment by frostxn** [comment]
> I didn't know your name, it's not all skidded anyway

are you serious? all you did is make the background move with the cursor and like anyone can do that.
